### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by laapsaap** [mauritsl/php-cassandra#1]
Hi,

Sorry for doing this using the Issue function. I cant find any info how to contact you otherwise.

How stable is this?  This is something half the world is looking for, but never find..

**Comment by mauritsl** [comment]
The code is very new, but doesn't suffer from known bugs. It's not yet in use on production environments, so extra testing may be required.

**Comment by laapsaap** [comment]
Thats great to hear, I will spread the news and play with it this week. How do you think the performance is compared to those php bindings that uses thrift approach?

Thanks for the share!

**Comment by mauritsl** [comment]
I've not tested performance yet, but will do.
It's using the lightweight binary protocol, where native PHP functions (pack / unpack) are used where possible. Performance should be good, but off course will be slower than native PHP extensions. And connection pooling is impossible to implement in stateless PHP, but that's valid for all PHP bindings.

I'm working on query abstraction as well. This is the basic concept:

$rows = $cassandra->get('table')
  ->fields(array('field', 'field'))
  ->filter('field', 'uuid', 'value')
  ->orderBy('field')
  ->consistency(Cassandra::CONSISTENCY_QUORUM)
  ->execute();

Not sure about the serialization yet. Most SQL abstraction layers tend to serialize every value as a string, with quotes. That is not allowed in Cassandra, so we have to specify a type for proper serialization.

**Comment by mauritsl** [comment]
Bugs have been fixed by this merge request:
https://github.com/mauritsl/php-cassandra/pull/3

Bad performance was due to Nagle's algorithm and is fixed as well.
